### ISSUE TITLE
LINK : fatal error LNK1104: cannot open file 'kernel32.lib'

### ISSUE THREAD

**Issue by helena-panda** [tehruhn/bofin#9]
I have VS2022 installed, but I receive the following error:
（when i run jupyter notebook for  the file: example-1e-Spin-bath-model-very-strong-coupling）
How can i do for this issues?

ImportError: Building module rhs78040 failed: ["distutils.errors.LinkError: command 'C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2022\\\\BuildTools\\\\VC\\\\Tools\\\\MSVC\\\\14.31.31103\\\\bin\\\\HostX86\\\\x64\\\\link.exe' failed with exit code 1104\n"]

**Comment by helena-panda** [comment]
Hi, it's ok now.
thanks

**Comment by nwlambert** [comment]
hi!

Seems like you sorted this out, but just fyi, there is an updated version of bofin now incorporated into qutip 4.7 directly.  It features  better optimization, and some cleaner interfaces to the ADOs and things.  You can check out the docs here https://qutip.org/docs/latest/guide/guide-heom.html   and the updated notebook examples in the qutip-notebooks repository.
